{% set version = "0.5.0" %}

package:
  name: ipfsspec
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/i/ipfsspec/ipfsspec-{{ version }}.tar.gz
  sha256: 398591cabad2335f64071bd57aebf287fef54bbabe74e82ab0577b252d66f05d

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - aiohttp
    - fsspec >=0.9.0
    - requests

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - ipfsspec

about:
  home: https://github.com/fsspec/ipfsspec
  license: MIT
  license_file: LICENSE
  summary: A readonly implementation of fsspec for IPFS

extra:
  recipe-maintainers:
    - raybellwaves
